#pragma once
const char* vertexShaderSource = "#version 120\n"
"attribute vec3 aPos;\n"
"attribute vec2 aTexCoord;\n"
"attribute vec3 aNormal;\n"
"varying vec2 TexCoord;\n"
"varying vec3 Normal;\n"
"uniform mat4 matrix;\n"
"uniform mat4 modelMat;\n"
"void main()\n"
"{\n"
"    gl_Position = matrix * (vec4(aPos, 1.0));\n"
"    TexCoord = aTexCoord;\n"
"    \n"
"    Normal = mat3(modelMat) * aNormal;\n" //basicamente trasladamos las normales lo mismo que transformamos todo el modelo para tener iluminacion realista en vez de quedarse "pegada"
"}\n";

const char* fragmentShaderSource = "#version 120\n"
"varying vec2 TexCoord;\n"
"varying vec3 Normal;\n"
"uniform sampler2D texture0;\n"
"uniform sampler2D texture1;\n"
"void main()\n"
"{\n"
"    float ambientStrength = 0.2;\n" //calculamos la luz de ambiente
"    vec3 lightColor = vec3(1.0, 1.0, 1.0);\n"
"    vec3 ambient = ambientStrength * lightColor;\n"
"    \n"
"    vec3 norm = normalize(Normal);\n" //calculamos luz direccional
"    vec3 lightDir = normalize(vec3(0.5, 1.0, 0.3));\n"
"    float diff = max(dot(norm, lightDir), 0.0);\n"
"    vec3 diffuse = diff * lightColor;\n"
"    \n"
"    vec4 color0 = texture2D(texture0, TexCoord);\n" //las texturas y eso
"    vec4 color1 = texture2D(texture1, TexCoord);\n"
"    vec4 objectColor = color0;\n"
"    if (color1.a > 0.0) {\n"
"        objectColor = mix(color0, color1, 0.5);\n"
"    }\n"
"    vec3 lighting = (ambient + diffuse);\n" //juntamos todo, bendito sea marco antonio y las clases de ilm por hacerme entender como funciona la luz
"    vec3 result = lighting * objectColor.rgb;\n"
"    gl_FragColor = vec4(result, objectColor.a);\n"
"}\n";

const char* visualizeNormalsVertexShaderSource = "#version 120\n"
"attribute vec3 aPos;\n"
"attribute vec2 aTexCoord;\n"
"attribute vec3 aNormal;\n"
"varying vec2 TexCoord;\n"
"varying vec3 Normal;\n"
"uniform mat4 matrix;\n"
"void main()\n"
"{\n"
"    gl_Position = matrix * (vec4(aPos, 1.0));\n"
"    TexCoord = aTexCoord;\n"
"    \n"
"    Normal = aNormal;\n" //basicamente trasladamos las normales lo mismo que transformamos todo el modelo para tener iluminacion realista en vez de quedarse "pegada"
"}\n";

const char* visualizeNormalsFragmentShaderSource = "#version 120\n"
"varying vec2 TexCoord;\n"
"varying vec3 Normal;\n"
"uniform sampler2D texture0;\n"
"uniform sampler2D texture1;\n"
"void main()\n"
"{\n"
"    vec3 norm = normalize(Normal) * 0.5 + 0.5;"
"    gl_FragColor = vec4(norm, 1.0);\n"
"}\n";